const API_END_POINTS = {
  V1: "/v1",
  USER_LOGIN: "/users/login",
  SIGN_UP: "/users/signup",
  CREATE_USER_THROUGH_INVITE: "/users/createUser",
  REFRESH_TOKEN: "/users/refreshToken",
  USERS: "/users",
  CONTACTS: "/contacts",
  PROFILE: "/profile",
  SHOUTOUTS: "/shoutouts",
  ME: "/me",
  CHANGE_PASSWORD: "/changePassword",
  FORGET_PASSWORD: "/forgetPassword",
  UPDATE_USER: "/updateUser",
  GET_COUNTRIES: "/getCountries",
  GET_STATES: "/getStatesByCode",
  GET_SKILLS: "/getSkills",
  UPDATE_USER_SKILLS: "/updateUserSkills",
  CREATE_EXPERIANCE: "/createExperiance",
  UPDATE_EXPERIANCE: "/updateExperiance",
  DELETE_EXPERIANCE: "/deleteExperiance",
  CREATE_EDUCATION: "/createEducation",
  UPDATE_EDUCATION: "/updateEducation",
  DELETE_EDUCATION: "/deleteEducation",
  CREATE_LINK: "/createLink",
  UPDATE_LINK: "/updateLink",
  DELETE_LINK: "/deleteLink",
  INVITE: "/invite",
  GET_ALL_CONTACTS: "/getAllContacts",
  GET_ALL_REQUESTS: "/getAllRequests",
  GET_ALL_INVITATION: "/getAllInvitation",
  GET_PHONEBOOK_FOR_JCU: "/getPhonebookForJCU",
  GET_PHONEBOOK_FOR_NON_JCU: "/getPhonebookForNonJCU",
  GET_ALL_NEWLY_JOINED: "/getAllNewlyJoined",
  GET_SUGGESTIONS: "/getSuggestions",
  SUMMERY: "/summery",
  ACCEPT_REQUEST: "/acceptRequest",
  SEND_REQUEST: "/sendRequest",
  DECLINE_REQUEST: "/declineRequest",
  INVITE_ALL_PHONEBOOK_CONTACTS: "/inviteAll",
  INVITE_PHONEBOOK_CONTACT: "/invitePhonebookContact",
  SEARCH: "/search",
  MESSAGE: "/message",
  CREATE_CONNECT: "/createConnect",
  CREATE: "/create",
  GET_DETAIL: "/getDetail",
  GET_CHAT_USERS: "/getChatUsers",
  SET_CONNECTED: "/setConnected",
  GRAPHQL: "/graphql",
  OFFSET: "?offset=",
  COUNTRY_CODE: "?countryCode=",
  LIMIT: "&limit=",
  SEARCH_TERM: "&searchTerm=",
  GET_CONTACT_REQUESTS: "/getContactRequests",
  CREATE_SHOUTOUT: "/createShoutout",
  UPDATE_SHOUTOUT: "/updateShoutout",
  DELETE_SHOUTOUT: "/deleteShoutout",
};

const API_METHODS = {
  GET: "GET",
  POST: "POST",
  PUT: "PUT",
  PATCH: "PATCH",
  DELETE: "DELETE",
};

export { API_END_POINTS, API_METHODS };
